# Generated by Django 4.0.5 on 2022-06-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('altitude', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('amount', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='coffees')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffees.coffeecategories')),
            ],
        ),
    ]
