# Generated by Django 4.0.5 on 2022-06-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffees", "0002_rename_coffeecategories_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="description",
            field=models.CharField(max_length=3000),
        ),
    ]
