# Generated by Django 4.0.5 on 2022-07-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='payment',
        ),
    ]
