# Generated by Django 4.0.5 on 2022-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_rename_paid_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="cost",
            field=models.FloatField(null=True),
        ),
    ]
