# Generated by Django 4.0.5 on 2022-07-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0006_order_total_price_orderitem_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
